SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'Constants' AS ObjectName, N'TABLE' AS ObjectType, N'DisplayPart' AS ColumnName, 1 AS NumberOfValuesInColumn, '2016-08-02 13:01:18.213' AS SearchDate, 'SELECT * FROM [dbo].[Constants] WHERE [DisplayPart] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'QueryItems' AS ObjectName, N'TABLE' AS ObjectType, N'Text' AS ColumnName, 1 AS NumberOfValuesInColumn, '2016-08-02 13:01:20.797' AS SearchDate, 'SELECT * FROM [dbo].[QueryItems] WHERE [Text] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_ChangeSet' AS ObjectName, N'TABLE' AS ObjectType, N'Comment' AS ColumnName, 1 AS NumberOfValuesInColumn, '2016-08-02 13:02:01.473' AS SearchDate, 'SELECT * FROM [dbo].[tbl_ChangeSet] WHERE [Comment] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_EventType' AS ObjectName, N'TABLE' AS ObjectType, N'EventTypeSchema' AS ColumnName, 3 AS NumberOfValuesInColumn, '2016-08-02 13:02:55.900' AS SearchDate, 'SELECT * FROM [dbo].[tbl_EventType] WHERE [EventTypeSchema] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_Message' AS ObjectName, N'TABLE' AS ObjectType, N'MessageText' AS ColumnName, 1 AS NumberOfValuesInColumn, '2016-08-02 13:05:29.193' AS SearchDate, 'SELECT * FROM [dbo].[tbl_Message] WHERE [MessageText] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_Parameter' AS ObjectName, N'TABLE' AS ObjectType, N'ParameterValue' AS ColumnName, 12 AS NumberOfValuesInColumn, '2016-08-02 13:05:32.310' AS SearchDate, 'SELECT * FROM [dbo].[tbl_Parameter] WHERE [ParameterValue] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_PendingChange' AS ObjectName, N'TABLE' AS ObjectType, N'CommittedChildItem' AS ColumnName, 3 AS NumberOfValuesInColumn, '2016-08-02 13:05:32.460' AS SearchDate, 'SELECT * FROM [dbo].[tbl_PendingChange] WHERE [CommittedChildItem] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_PendingChange' AS ObjectName, N'TABLE' AS ObjectType, N'TargetChildItem' AS ColumnName, 8 AS NumberOfValuesInColumn, '2016-08-02 13:05:32.460' AS SearchDate, 'SELECT * FROM [dbo].[tbl_PendingChange] WHERE [TargetChildItem] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_TestResolutionState' AS ObjectName, N'TABLE' AS ObjectType, N'Name' AS ColumnName, 6 AS NumberOfValuesInColumn, '2016-08-02 13:06:45.757' AS SearchDate, 'SELECT * FROM [dbo].[tbl_TestResolutionState] WHERE [Name] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_WorkItemCustomLatest' AS ObjectName, N'TABLE' AS ObjectType, N'StringValue' AS ColumnName, 1170 AS NumberOfValuesInColumn, '2016-08-02 13:07:35.110' AS SearchDate, 'SELECT * FROM [dbo].[tbl_WorkItemCustomLatest] WHERE [StringValue] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_Workspace' AS ObjectName, N'TABLE' AS ObjectType, N'WorkspaceName' AS ColumnName, 1 AS NumberOfValuesInColumn, '2016-08-02 13:07:42.170' AS SearchDate, 'SELECT * FROM [dbo].[tbl_Workspace] WHERE [WorkspaceName] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'TreeProperties' AS ObjectName, N'TABLE' AS ObjectType, N'Value' AS ColumnName, 11 AS NumberOfValuesInColumn, '2016-08-02 13:07:43.700' AS SearchDate, 'SELECT * FROM [dbo].[TreeProperties] WHERE [Value] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'WorkItemFiles' AS ObjectName, N'TABLE' AS ObjectType, N'Comment' AS ColumnName, 1 AS NumberOfValuesInColumn, '2016-08-02 13:07:44.367' AS SearchDate, 'SELECT * FROM [dbo].[WorkItemFiles] WHERE [Comment] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'ext_vwChangesets' AS ObjectName, N'VIEW' AS ObjectType, N'Comment' AS ColumnName, 1 AS NumberOfValuesInColumn, '2016-08-02 13:08:48.990' AS SearchDate, 'SELECT * FROM [dbo].[ext_vwChangesets] WHERE [Comment] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'vw_denorm_WorkItemCustomAll' AS ObjectName, N'VIEW' AS ObjectType, N'StringValue' AS ColumnName, 1170 AS NumberOfValuesInColumn, '2016-08-02 13:10:20.190' AS SearchDate, 'SELECT * FROM [dbo].[vw_denorm_WorkItemCustomAll] WHERE [StringValue] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'vw_denorm_WorkItemCustomLatest' AS ObjectName, N'VIEW' AS ObjectType, N'StringValue' AS ColumnName, 1170 AS NumberOfValuesInColumn, '2016-08-02 13:10:26.720' AS SearchDate, 'SELECT * FROM [dbo].[vw_denorm_WorkItemCustomLatest] WHERE [StringValue] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'vw_WorkItemCustomAll' AS ObjectName, N'VIEW' AS ObjectType, N'StringValue' AS ColumnName, 1170 AS NumberOfValuesInColumn, '2016-08-02 13:11:31.610' AS SearchDate, 'SELECT * FROM [dbo].[vw_WorkItemCustomAll] WHERE [StringValue] LIKE N''%needs%''' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'CodeSense' AS ObjectSchema, N'tbl_AggregateMap' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:01:16.026' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_BuildInformation2' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:02:00.390' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_Content' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:02:55.300' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_FileMetadata' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:03:26.112' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_FileReference' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:03:56.121' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_LabelEntry' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:04:28.618' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_LocalVersion' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:04:58.634' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_MergeHistory' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:05:28.756' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_PropertyValue' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:06:27.927' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'tbl_Version' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:07:26.283' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'WorkItemLongTexts' AS ObjectName, N'TABLE' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:08:16.954' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'ext_vwChangesCommands' AS ObjectName, N'VIEW' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:08:48.244' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'vw_denorm_WorkItemCoreAll' AS ObjectName, N'VIEW' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:09:45.054' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'vw_denorm_WorkItemCoreWere' AS ObjectName, N'VIEW' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:10:19.942' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'vw_IndexedVersion' AS ObjectName, N'VIEW' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:11:02.707' AS SearchDate, '' AS SqlQueryForSearchedValue UNION ALL 
SELECT N'%needs%' AS SearchText, N'dbo' AS ObjectSchema, N'vw_WorkItemFileCountWere' AS ObjectName, N'VIEW' AS ObjectType, N'ERROR!: Timeout expirado. O timeout esgotou antes da conclusão da operação ou o servidor não está respondendo.; O tempo limite de espera foi atingido; ' AS ColumnName, -1 AS NumberOfValuesInColumn, '2016-08-02 13:12:19.294' AS SearchDate, '' AS SqlQueryForSearchedValue 